services:
  simple-docker-controller:
    image: simple-docker-controller
    user: "1001:999" # create a user (1001) and make them a member of the docker group (999 in this case) 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-docker-controller
    environment:
      - DOCKER_SOCK_URI=unix:///var/run/docker.sock # Set according to OS/docker instance - https://github.com/dotnet/Docker.DotNet/blob/master/README.md
      - SIMPLE_LIST=true  # Set this to "true" to only return the container names and their statuses
      - ASPNETCORE_ENVIRONMENT=Development  # Enable development features
      - KILL_SELF=false # If normal shutdown not working can attempt to kill own container (default false)
      - ALLOW_LIST=true # Should allow listing of running containers via endpoint (default false)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"